version: '3.8'

services:
  aircraft_ops_tool:
    build: .
    ports:
      - "8086:5150"
    volumes:
      - ./data:/app/data
      - flask_secret:/run/secrets
    restart: unless-stopped

volumes:
  flask_secret:
