services:
  aircraft_ops_tool:
    image: ghcr.io/xmutantson/aircraft_ops_tool:latest
    network_mode: host    # expose container directly on host LAN
    volumes:
      - ./data:/app/data  # persist SQLite DB
      - flask_secret:/run/secrets
    restart: unless-stopped

volumes:
  flask_secret:
