[tool.ruff]
target-version = "py310"
line-length = 100
extend-exclude = [".venv", "venv", "__pycache__", "node_modules", "reports", "tools", "*bak*", "*bak.*"]

[tool.ruff.lint]
# Only the high-signal families:
select = ["E9", "F63", "F7", "F82"]
# Silence the rest of the noise you called out:
ignore = [
  "F401","F403","F405","F811","F841",   # unused, star-import, may-be-undefined-from-star, redefs
  "E401","E402","E701","E702","E722"    # import/style one-liners, bare except
]

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
warn_unused_ignores = true
warn_unreachable = true
